"""Pydantic schemas for the agent analysis pipeline.

AgentVerdict matches the JSON output format defined in persona Markdown templates
exactly. CommitteeReport and CIODecision are downstream aggregation schemas
built by Plans 03-02 and 03-03 respectively.
"""

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class AgentVerdict(BaseModel):
    """Per-persona investment verdict.

    Fields match the output_format section of every persona Markdown template.
    The LLM is instructed to return exactly these keys — any deviation causes a
    validation error from messages.parse(), which surfaces as LLMCallError.
    """

    persona: str
    verdict: Literal["BUY", "HOLD", "PASS"]
    confidence: int = Field(ge=0, le=100)
    rationale: str
    key_metrics_used: List[str]
    risks: List[str]
    upside_scenario: str
    time_horizon: str
    data_gaps: List[str]


class CommitteeReport(BaseModel):
    """Aggregated report from all five persona agents.

    Built by the committee task in Plan 03-02 after all AgentVerdicts arrive.
    """

    opportunity_id: str
    verdicts: List[AgentVerdict]
    consensus: Literal["BUY", "HOLD", "PASS", "SPLIT"]
    dissent_agents: List[str]
    variance_score: float
    weighted_conviction: float
    asymmetric_flag: bool
    asymmetric_justification: Optional[str] = None


class CIODecision(BaseModel):
    """CIO-level final decision synthesised from the CommitteeReport.

    Generated by the CIO agent in Plan 03-03. conviction_score and
    suggested_allocation_pct drive the portfolio manager in Phase 4.
    """

    opportunity_id: str
    conviction_score: int = Field(ge=0, le=100)
    suggested_allocation_pct: float = Field(ge=0.0, le=100.0)
    time_horizon: str
    risk_rating: Literal["LOW", "MEDIUM", "HIGH", "VERY_HIGH"]
    key_catalysts: List[str]
    kill_conditions: List[str]
    final_verdict: Literal["INVEST", "MONITOR", "PASS"]
